service: chargeflow-microservice-products
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1

functions:
  productsApi:
    handler: microservices/products/handler.handler
    events:
      - http:
          path: /products/{any+}
          method: get
          cors: true
      - http:
          path: /products
          method: get
          cors: true
      - http:
          path: /products/{any+}
          method: post
          cors: true
      - http:
          path: /customer/{any+}
          method: get
          cors: true
      - http:
          path: /customer
          method: get
          cors: true
      - http:
          path: /customer/{any+}
          method: post
          cors: true