service: chargeflow
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x

custom:
  serverless-offline:
    useChildProcesses: true

functions:
  api:
    handler: microservices/products/handler.handler
    events:
      - http:
          path: /products/{any+}
          method: get
          cors: true
      - http:
          path: /products/{any+}
          method: post
          cors: true
      - http:
          path: /customer/{any+}
          method: get
          cors: true
      - http:
          path: /customer/{any+}
          method: post
          cors: true