service: chargeflow-microservice-products
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1

functions:
  checkoutsApi:
    handler: microservices/checkouts/handler.handler
    events:
      - http:
          path: /checkouts/{any+}
          method: get
          cors: true
      - http:
          path: /checkouts/{any+}
          method: post
          cors: true
      - http:
          path: /checkouts/{any+}
          method: put
          cors: true
