service: chargeflow-microservice-emails
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1
  environment:
    ENV_AWS_REGION: ${env:ENV_AWS_REGION}
    ENV_AWS_ACCESS_KEY_ID: ${env:ENV_AWS_ACCESS_KEY_ID}
    ENV_AWS_SECRET_ACCESS_KEY: ${env:ENV_AWS_SECRET_ACCESS_KEY}
    MONGODB_CONNECTION_URL: ${env:MONGODB_CONNECTION_URL}
    EMAIL_QUEUE_URL: ${env:EMAIL_QUEUE_URL}
    BASE_URL: ${env:BASE_URL}

functions:
  checkoutEmailQueue:
    handler: microservices/emails/handler.emailHandler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - CheckoutEmailQueue
              - Arn

resources:
  Resources:
    CheckoutEmailQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "CheckoutEmailQueue"
